<a href="https://colab.research.google.com/github/alfinmaulani/skripsi/blob/master/2_2glove2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import io
import os
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')


url1 = 'https://raw.githubusercontent.com/alfinmaulani/skripsi/master/dataisear(preputama).csv'
url2 = 'tba'
df = pd.read_csv(url1)
# df.iloc[:,1]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [45]:
!pip install glove-python-binary

In [46]:
from glove import Glove
from glove import Corpus

In [47]:
df.emosi.value_counts()

joy        1092
sadness    1082
anger      1079
fear       1076
shame      1071
disgust    1066
guilt      1050
Name: emosi, dtype: int64

In [48]:
sentences = [word_tokenize(x) for x in df.dokumen] 

In [49]:
df.dokumen

0       on days when i feel close to my partner and ot...
1       every time i imagine that someone i love or i ...
2       when i had been obviously unjustly treated and...
3       when i think about the short time that we live...
4       at a gathering i found myself involuntarily si...
                              ...                        
7511    two years back someone invited me to be the tu...
7512    i had taken the responsibility to do something...
7513    i was at home and i heard a loud sound of spit...
7514    i did not do the homework that the teacher had...
7515    i had shouted at my younger brother and he was...
Name: dokumen, Length: 7516, dtype: object

In [50]:
korpus = Corpus()
korpus.fit(sentences, window=10, ignore_missing=False)
# korpus.save('glove.model')

In [ ]:
korpus.dictionary

In [ ]:
# corpus_model = Corpus.load('glove.model')

In [52]:
korpus
# corpus_model

In [53]:
len(korpus.dictionary)

9352

In [54]:
korpus.matrix

<9352x9352 sparse matrix of type '<class 'numpy.float64'>'
	with 400898 stored elements in COOrdinate format>

In [55]:
glove = Glove(no_components=100, learning_rate=0.05, alpha=0.75, max_count=100, max_loss=10.0, random_state=None)
glove.fit(korpus.matrix)
glove.add_dictionary(korpus.dictionary)

In [63]:
glove.save('glove.model')

In [56]:
glove

In [13]:
glove.word_vectors

array([[-2.34474774e-02, -2.00683398e-01, -2.46898295e-01, ...,
        -1.78302576e-01, -1.72343204e-01, -1.04842518e-01],
       [-9.58242894e-03, -7.76613627e-02, -8.78979284e-02, ...,
        -6.40624163e-02, -5.93609954e-02, -4.06558985e-02],
       [-1.12341269e-01, -2.71889839e-01, -3.31551970e-01, ...,
        -2.58786101e-01, -2.54880265e-01, -1.65551829e-01],
       ...,
       [ 9.87097166e-04,  1.13871451e-02,  1.31365841e-02, ...,
         7.23698275e-03,  8.07332501e-03,  2.53575585e-04],
       [ 3.26751468e-03,  5.78238824e-03,  1.31165921e-02, ...,
         1.37505928e-02,  1.36685431e-02,  3.81072465e-03],
       [ 3.27733057e-03,  5.47956208e-03,  6.89103051e-03, ...,
         1.54705105e-03,  5.69275338e-05,  3.85085208e-03]])

In [57]:
glove.word_vectors.shape

(9352, 100)

In [ ]:
glove.most_similar('i', number=10)

[('am', 0.997013081204825),
 ('realized', 0.995790314416636),
 ('think', 0.995535752590722),
 ('remember', 0.9953009800019226),
 ('knew', 0.9951777906668989),
 ('feel', 0.994664290865196),
 ('never', 0.9939717111259972),
 ('should', 0.9938763148105081),
 ('feared', 0.9937647653626294)]

In [15]:
glove.word_vectors[glove.dictionary['me']]

array([-0.03255904, -0.24741555, -0.32917131, -0.25710498,  0.17819011,
        0.13116598, -0.2656656 , -0.05031443, -0.03726894, -0.1242091 ,
       -0.29505749, -0.13472902, -0.23668658,  0.20678415, -0.03136584,
       -0.02908277,  0.11536859, -0.08801572,  0.26362637,  0.26598555,
       -0.00337509,  0.18809174, -0.25143509,  0.18910896, -0.00291719,
       -0.12587793, -0.04850888, -0.12676655, -0.2657141 ,  0.28480549,
       -0.08991637, -0.20771582,  0.18903267,  0.02648139, -0.27163516,
       -0.26671358,  0.15242992, -0.03938952, -0.27974181, -0.04234029,
       -0.3183729 ,  0.02290336, -0.09149297, -0.00190616,  0.16570145,
       -0.2985235 , -0.06980545, -0.0935501 , -0.16742645, -0.0248719 ,
       -0.14596632, -0.21626633,  0.06799297,  0.23632975, -0.0387019 ,
        0.17037057, -0.22727442,  0.05179288, -0.03672119, -0.12621835,
        0.10938573,  0.2646735 , -0.1543997 , -0.18313716,  0.2720704 ,
        0.06412225, -0.05548513,  0.16913055,  0.13686685,  0.16

In [ ]:
sentences

In [ ]:
# def eksfit(sentence, model):
#   vec = [model[word] for word in word_tokenize(sentence)]
#   sent_vec = np.mean(vec, axis=0)
#   return sent_vec

In [ ]:
word='me'
glove.word_vectors[glove.dictionary[word]]

In [31]:
a=[1,2,3]
b=[2,3,4]
print(np.add(a,b))

[3 5 7]


In [60]:
import array
ekstrak=[]
temp=array.array('i',(0,)*100)
for senten in sentences:
  for word in senten:
    temp=np.add(temp,glove.word_vectors[glove.dictionary[word]])
  temp=temp/len(senten)
  ekstrak.append(temp)

In [61]:
np.shape(ekstrak)

(7516, 100)

In [ ]:
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.scripts.glove2word2vec import get_glove_info
from gensim.models import Word2Vec
import gensim

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
get_glove_info('/content/drive/MyDrive/glove.6B.100d.txt')

(400000, 100)

In [ ]:
get_glove_info('/content/glovetrain.model')

(58473, 5)

In [ ]:
glove.word_vectors.shape

(9352, 100)

In [ ]:
# glove_file = '/content/glove.model'
glove_file = '/content/drive/MyDrive/glove.6B.100d.txt'
tmp_file = '/content/tes'

glove2word2vec(glove_file, tmp_file)

# KeyedVectors.load_word2vec_format dipakai jika c
model = KeyedVectors.load_word2vec_format(tmp_file)
# model = KeyedVectors.load_word2vec_format(tmp_file,binary=True, unicode_errors='ignore',limit=41500)
# model = gensim.models.word2vec.Word2Vec.load(tmp_file)

In [ ]:
model.wv.vectors

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


array([[-0.038194, -0.24487 ,  0.72812 , ..., -0.1459  ,  0.8278  ,
         0.27062 ],
       [-0.10767 ,  0.11053 ,  0.59812 , ..., -0.83155 ,  0.45293 ,
         0.082577],
       [-0.33979 ,  0.20941 ,  0.46348 , ..., -0.23394 ,  0.47298 ,
        -0.028803],
       ...,
       [ 0.36088 , -0.16919 , -0.32704 , ...,  0.27139 , -0.29188 ,
         0.16109 ],
       [-0.10461 , -0.5047  , -0.49331 , ...,  0.42527 , -0.5125  ,
        -0.17054 ],
       [ 0.28365 , -0.6263  , -0.44351 , ...,  0.43678 , -0.82607 ,
        -0.15701 ]], dtype=float32)

In [ ]:
model.wv.vectors.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


(400000, 100)

In [ ]:
model.wv.vocab

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


{'the': <gensim.models.keyedvectors.Vocab at 0x7ff942999550>,
 ',': <gensim.models.keyedvectors.Vocab at 0x7ff942987d50>,
 '.': <gensim.models.keyedvectors.Vocab at 0x7ff942999590>,
 'of': <gensim.models.keyedvectors.Vocab at 0x7ff942993ad0>,
 'to': <gensim.models.keyedvectors.Vocab at 0x7ff9429995d0>,
 'and': <gensim.models.keyedvectors.Vocab at 0x7ff942993710>,
 'in': <gensim.models.keyedvectors.Vocab at 0x7ff9429996d0>,
 'a': <gensim.models.keyedvectors.Vocab at 0x7ff942993a50>,
 '"': <gensim.models.keyedvectors.Vocab at 0x7ff942999690>,
 "'s": <gensim.models.keyedvectors.Vocab at 0x7ff9429930d0>,
 'for': <gensim.models.keyedvectors.Vocab at 0x7ff942999750>,
 '-': <gensim.models.keyedvectors.Vocab at 0x7ff942993a90>,
 'that': <gensim.models.keyedvectors.Vocab at 0x7ff942999710>,
 'on': <gensim.models.keyedvectors.Vocab at 0x7ff942993050>,
 'is': <gensim.models.keyedvectors.Vocab at 0x7ff9429997d0>,
 'was': <gensim.models.keyedvectors.Vocab at 0x7ff942993d90>,
 'said': <gensim.models