<a href="https://colab.research.google.com/github/alfinmaulani/skripsi/blob/master/2_2glove2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
import io
import os
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')


url1 = 'https://raw.githubusercontent.com/alfinmaulani/skripsi/master/dataisear(preputama).csv'
url2 = 'tba'
df = pd.read_csv(url1)
# df.iloc[:,1]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [15]:
!pip install glove-python-binary

In [16]:
from glove import Glove
from glove import Corpus

In [17]:
df.emosi.value_counts()

joy        1092
sadness    1082
anger      1079
fear       1076
shame      1071
disgust    1066
guilt      1050
Name: emosi, dtype: int64

In [18]:
sentences = [word_tokenize(x) for x in df.dokumen] 

In [19]:
df.dokumen

0       on days when i feel close to my partner and ot...
1       every time i imagine that someone i love or i ...
2       when i had been obviously unjustly treated and...
3       when i think about the short time that we live...
4       at a gathering i found myself involuntarily si...
                              ...                        
7511    two years back someone invited me to be the tu...
7512    i had taken the responsibility to do something...
7513    i was at home and i heard a loud sound of spit...
7514    i did not do the homework that the teacher had...
7515    i had shouted at my younger brother and he was...
Name: dokumen, Length: 7516, dtype: object

In [20]:
korpus = Corpus()
korpus.fit(sentences, window=10, ignore_missing=False)
# korpus.save('glove.model')

In [ ]:
korpus.dictionary

In [ ]:
# corpus_model = Corpus.load('glove.model')

In [21]:
korpus
# corpus_model

In [22]:
len(korpus.dictionary)

9352

In [23]:
korpus.matrix

<9352x9352 sparse matrix of type '<class 'numpy.float64'>'
	with 400898 stored elements in COOrdinate format>

In [24]:
glove = Glove(no_components=100, learning_rate=0.05, alpha=0.75, max_count=100, max_loss=10.0, random_state=None)
glove.fit(korpus.matrix)
glove.add_dictionary(korpus.dictionary)

In [33]:
glove.save('glovetrain.model')

In [25]:
glove

In [26]:
glove.word_vectors

array([[ 1.74049202e-01,  1.95153129e-01, -4.90285794e-02, ...,
         2.41035813e-03, -8.04117181e-03, -8.44690644e-02],
       [ 5.30446660e-02,  7.26038123e-02, -2.53548129e-02, ...,
        -7.03880256e-03,  1.52074729e-03, -2.56645616e-02],
       [ 2.20056290e-01,  2.61590926e-01, -8.49792812e-02, ...,
         3.68232718e-02,  6.27856823e-02, -1.46146015e-01],
       ...,
       [-1.32339818e-02, -8.85826422e-03,  5.93105250e-03, ...,
        -1.28853948e-03, -1.11588094e-03,  4.69649934e-03],
       [-1.14033454e-02, -1.29569005e-02,  2.08717403e-03, ...,
        -1.44314167e-03, -2.21161966e-03,  4.77022601e-03],
       [-4.34060167e-03, -3.62128944e-03,  2.42994333e-03, ...,
        -1.74637710e-04, -4.35472883e-03,  1.88508184e-03]])

In [27]:
glove.word_vectors.shape

(9352, 100)

In [28]:
glove.most_similar('i', number=10)

[('am', 0.997013081204825),
 ('realized', 0.995790314416636),
 ('think', 0.995535752590722),
 ('remember', 0.9953009800019226),
 ('knew', 0.9951777906668989),
 ('feel', 0.994664290865196),
 ('never', 0.9939717111259972),
 ('should', 0.9938763148105081),
 ('feared', 0.9937647653626294)]

In [29]:
glove.word_vectors[glove.dictionary['me']]

array([ 0.21101566,  0.24110409, -0.04693343,  0.11089692, -0.2125009 ,
       -0.04416068, -0.04734862,  0.11622745,  0.08523445, -0.03760745,
        0.01127925,  0.20231296, -0.23013394, -0.06621343,  0.1320726 ,
        0.03871423,  0.12363733, -0.25990031,  0.02265145, -0.12238869,
        0.16136212, -0.02332084,  0.37054944, -0.18073219,  0.09846218,
       -0.32491269,  0.33367064,  0.2121584 , -0.20657469, -0.22420288,
        0.21082487, -0.24125346, -0.16947292, -0.10286602,  0.09930358,
        0.07081073, -0.13689894,  0.14650123,  0.16531924,  0.05375397,
       -0.08506603,  0.18226021,  0.06627979,  0.14300488,  0.25560326,
        0.15528039, -0.23584605, -0.02614171, -0.33538306, -0.09473061,
        0.13164926,  0.3513921 , -0.26357273, -0.23350722,  0.27946674,
        0.17987505,  0.20992405, -0.19880283, -0.13702893,  0.06326275,
        0.12562889, -0.07406369,  0.30286855, -0.14984483,  0.19589451,
       -0.1022308 ,  0.23723044, -0.17395135,  0.17866621,  0.27

In [30]:
glove

In [ ]:
# tes1='friends'
# tes2=['my', ' friend']
# tes3='my friend'

# glove.transform_paragraph(tes1)

In [31]:
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.scripts.glove2word2vec import get_glove_info
from gensim.models import Word2Vec
import gensim

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [37]:
get_glove_info('/content/drive/MyDrive/glove.6B.100d.txt')

(400000, 100)

In [39]:
get_glove_info('/content/glovetrain.model')

(58473, 5)

In [35]:
glove.word_vectors.shape

(9352, 100)

In [90]:
# glove_file = '/content/glove.model'
glove_file = '/content/drive/MyDrive/glove.6B.100d.txt'
tmp_file = '/content/tes'

glove2word2vec(glove_file, tmp_file)

# KeyedVectors.load_word2vec_format dipakai jika c
model = KeyedVectors.load_word2vec_format(tmp_file)
# model = KeyedVectors.load_word2vec_format(tmp_file,binary=True, unicode_errors='ignore',limit=41500)
# model = gensim.models.word2vec.Word2Vec.load(tmp_file)

In [91]:
model.wv.vectors

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


array([[-0.038194, -0.24487 ,  0.72812 , ..., -0.1459  ,  0.8278  ,
         0.27062 ],
       [-0.10767 ,  0.11053 ,  0.59812 , ..., -0.83155 ,  0.45293 ,
         0.082577],
       [-0.33979 ,  0.20941 ,  0.46348 , ..., -0.23394 ,  0.47298 ,
        -0.028803],
       ...,
       [ 0.36088 , -0.16919 , -0.32704 , ...,  0.27139 , -0.29188 ,
         0.16109 ],
       [-0.10461 , -0.5047  , -0.49331 , ...,  0.42527 , -0.5125  ,
        -0.17054 ],
       [ 0.28365 , -0.6263  , -0.44351 , ...,  0.43678 , -0.82607 ,
        -0.15701 ]], dtype=float32)

In [93]:
model.wv.vectors.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


(400000, 100)

In [94]:
model.wv.vocab

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


{'the': <gensim.models.keyedvectors.Vocab at 0x7ff942999550>,
 ',': <gensim.models.keyedvectors.Vocab at 0x7ff942987d50>,
 '.': <gensim.models.keyedvectors.Vocab at 0x7ff942999590>,
 'of': <gensim.models.keyedvectors.Vocab at 0x7ff942993ad0>,
 'to': <gensim.models.keyedvectors.Vocab at 0x7ff9429995d0>,
 'and': <gensim.models.keyedvectors.Vocab at 0x7ff942993710>,
 'in': <gensim.models.keyedvectors.Vocab at 0x7ff9429996d0>,
 'a': <gensim.models.keyedvectors.Vocab at 0x7ff942993a50>,
 '"': <gensim.models.keyedvectors.Vocab at 0x7ff942999690>,
 "'s": <gensim.models.keyedvectors.Vocab at 0x7ff9429930d0>,
 'for': <gensim.models.keyedvectors.Vocab at 0x7ff942999750>,
 '-': <gensim.models.keyedvectors.Vocab at 0x7ff942993a90>,
 'that': <gensim.models.keyedvectors.Vocab at 0x7ff942999710>,
 'on': <gensim.models.keyedvectors.Vocab at 0x7ff942993050>,
 'is': <gensim.models.keyedvectors.Vocab at 0x7ff9429997d0>,
 'was': <gensim.models.keyedvectors.Vocab at 0x7ff942993d90>,
 'said': <gensim.models