<a href="https://colab.research.google.com/github/alfinmaulani/skripsi/blob/master/2_2glove2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np
import pandas as pd
import io
import os
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')


url1 = 'https://raw.githubusercontent.com/alfinmaulani/skripsi/master/dataisear(preputama).csv'
url2 = 'tba'
df = pd.read_csv(url1)
# df.iloc[:,1]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [32]:
!pip install glove-python-binary

In [33]:
from glove import Glove
from glove import Corpus

In [34]:
df.emosi.value_counts()

joy        1092
sadness    1082
anger      1079
fear       1076
shame      1071
disgust    1066
guilt      1050
Name: emosi, dtype: int64

In [35]:
sentences = [word_tokenize(x) for x in df.dokumen] 

In [36]:
df.dokumen

0       on days when i feel close to my partner and ot...
1       every time i imagine that someone i love or i ...
2       when i had been obviously unjustly treated and...
3       when i think about the short time that we live...
4       at a gathering i found myself involuntarily si...
                              ...                        
7511    two years back someone invited me to be the tu...
7512    i had taken the responsibility to do something...
7513    i was at home and i heard a loud sound of spit...
7514    i did not do the homework that the teacher had...
7515    i had shouted at my younger brother and he was...
Name: dokumen, Length: 7516, dtype: object

In [37]:
korpus = Corpus()
korpus.fit(sentences, window=10, ignore_missing=False)
# korpus.save('glove.model')

In [38]:
korpus.dictionary

{'on': 0,
 'days': 1,
 'when': 2,
 'i': 3,
 'feel': 4,
 'close': 5,
 'to': 6,
 'my': 7,
 'partner': 8,
 'and': 9,
 'other': 10,
 'friends': 11,
 'at': 12,
 'peace': 13,
 'with': 14,
 'myself': 15,
 'also': 16,
 'experience': 17,
 'a': 18,
 'contact': 19,
 'people': 20,
 'whom': 21,
 'regard': 22,
 'greatly': 23,
 'every': 24,
 'time': 25,
 'imagine': 26,
 'that': 27,
 'someone': 28,
 'love': 29,
 'or': 30,
 'could': 31,
 'serious': 32,
 'illness': 33,
 'even': 34,
 'death': 35,
 'had': 36,
 'been': 37,
 'obviously': 38,
 'unjustly': 39,
 'treated': 40,
 'no': 41,
 'possibility': 42,
 'of': 43,
 'elucidating': 44,
 'this': 45,
 'think': 46,
 'about': 47,
 'the': 48,
 'short': 49,
 'we': 50,
 'live': 51,
 'relate': 52,
 'it': 53,
 'periods': 54,
 'life': 55,
 'did': 56,
 'not': 57,
 'use': 58,
 'gathering': 59,
 'found': 60,
 'involuntarily': 61,
 'sitting': 62,
 'next': 63,
 'two': 64,
 'who': 65,
 'expressed': 66,
 'opinions': 67,
 'considered': 68,
 'very': 69,
 'low': 70,
 'discrimin

In [ ]:
# corpus_model = Corpus.load('glove.model')

In [39]:
korpus
# corpus_model

In [40]:
len(korpus.dictionary)

9352

In [41]:
korpus.matrix

<9352x9352 sparse matrix of type '<class 'numpy.float64'>'
	with 400898 stored elements in COOrdinate format>

In [42]:
glove = Glove(no_components=100, learning_rate=0.05, alpha=0.75, max_count=100, max_loss=10.0, random_state=None)
glove.fit(korpus.matrix)
glove.add_dictionary(korpus.dictionary)
glove.save('glove.model')


In [43]:
glove

In [44]:
glove.most_similar('i', number=10)

[('knew', 0.9976477192160031),
 ('am', 0.9974291599232528),
 ('realized', 0.9970053274665215),
 ('thought', 0.9968076603101566),
 ('should', 0.9966902593320506),
 ('couldnt', 0.9966619664999298),
 ('feel', 0.9962648965757736),
 ('heard', 0.9961117430610662),
 ('didnt', 0.9959774809436786)]

In [45]:
glove.word_vectors[glove.dictionary['me']]

array([ 0.20894088,  0.20160939,  0.26508384,  0.1927371 , -0.14651802,
        0.27383447, -0.09266269,  0.1359848 ,  0.07925942, -0.12921977,
        0.32314702, -0.22463803,  0.23000046, -0.22980292,  0.17807375,
        0.22273489,  0.08885115, -0.16650816,  0.29022036, -0.11155406,
       -0.23011949,  0.21691843, -0.10016841, -0.16963861, -0.04993882,
        0.25298562,  0.32493546, -0.19487349, -0.29258486, -0.35226985,
        0.0570647 , -0.30353447, -0.16358372,  0.23491409, -0.0520626 ,
       -0.20913637, -0.00262646, -0.16667925,  0.1728972 , -0.0562746 ,
       -0.09480902, -0.12869584,  0.10761062,  0.05763188,  0.27667054,
       -0.0452335 ,  0.25123463, -0.13349426, -0.12592998,  0.06983922,
       -0.16026253, -0.13212768, -0.08835417, -0.05666458,  0.02219076,
        0.20301403,  0.12921908, -0.06956913,  0.09026353,  0.03560343,
       -0.14860807,  0.18380145, -0.11590684,  0.02232946, -0.27134797,
        0.15631068,  0.3273792 , -0.29375194,  0.22473591,  0.18

In [46]:
glove.word_vectors

array([[ 0.15023635,  0.1316675 ,  0.21117878, ..., -0.14757797,
        -0.18689867,  0.14853156],
       [ 0.05939901,  0.04556015,  0.07831745, ..., -0.0619439 ,
        -0.07603954,  0.05474599],
       [ 0.23467244,  0.20156254,  0.29295146, ..., -0.22842686,
        -0.29362946,  0.21661328],
       ...,
       [-0.01224976, -0.01220523, -0.01348603, ...,  0.00462596,
         0.0120249 , -0.01041328],
       [-0.0045423 , -0.00697319, -0.01184221, ...,  0.00732557,
         0.00724442, -0.00971916],
       [-0.0044687 , -0.00793263, -0.01011495, ...,  0.00731502,
         0.00368306, -0.0082171 ]])

In [47]:
glove.word_vectors.shape

(9352, 100)

In [68]:
glove

AttributeError: ignored

In [ ]:
# tes1='friends'
# tes2=['my', ' friend']
# tes3='my friend'

# glove.transform_paragraph(tes1)

In [19]:
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.scripts.glove2word2vec import get_glove_info
from gensim.models import Word2Vec
import gensim

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [50]:
get_glove_info('/content/drive/MyDrive/glove.6B.100d.txt')

(400000, 100)

In [52]:
get_glove_info('/content/glove.model')

(58924, 5)

In [71]:
glove_file = '/content/glove.model'
tmp_file = '/content/tes'

glove2word2vec(glove_file, tmp_file)

# KeyedVectors.load_word2vec_format dipakai jika c
model = KeyedVectors.load_word2vec_format(tmp_file,binary=True, unicode_errors='ignore',limit=9352)
# model = gensim.models.word2vec.Word2Vec.load(tmp_file)

In [72]:
model.wv.vectors

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


array([[-6.6678461e+02, -1.1713548e-26, -9.3391578e+04, -1.2224200e-27,
        -4.2755659e+05],
       [-5.8424762e+04,  1.0080260e+16, -7.0968428e-16, -3.1331840e-10,
        -3.7157341e-07],
       [-1.6084446e-29, -8.5082135e-14, -9.8529891e-34,  1.2438367e+35,
        -2.8793350e+25],
       ...,
       [ 9.5676678e-01, -3.7835398e+04,  1.1268523e+00, -6.5024461e-18,
        -9.3119448e-01],
       [ 1.0273114e+11,  2.4122879e+32, -5.1401392e+10,  6.0231556e+07,
        -3.2439038e-19],
       [-6.2719260e+06,  1.6779766e+16,  1.3784019e+19,  8.8002525e-33,
        -5.6282967e-37]], dtype=float32)

In [73]:
model.wv.vectors.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


(9280, 5)