<a href="https://colab.research.google.com/github/alfinmaulani/skripsi/blob/master/2_2glove2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import io
import os
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')


url1 = 'https://raw.githubusercontent.com/alfinmaulani/skripsi/master/dataisear(preputama).csv'
url2 = 'tba'
df = pd.read_csv(url1)
# df.iloc[:,1]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [2]:
!pip install glove-python-binary

     |████████████████████████████████| 948 kB 30.4 MB/s 


In [3]:
from glove import Glove
from glove import Corpus

In [4]:
df.emosi.value_counts()

joy        1092
sadness    1082
anger      1079
fear       1076
shame      1071
disgust    1066
guilt      1050
Name: emosi, dtype: int64

In [5]:
sentences = [word_tokenize(x) for x in df.dokumen] 

In [6]:
df.dokumen

0       on days when i feel close to my partner and ot...
1       every time i imagine that someone i love or i ...
2       when i had been obviously unjustly treated and...
3       when i think about the short time that we live...
4       at a gathering i found myself involuntarily si...
                              ...                        
7511    two years back someone invited me to be the tu...
7512    i had taken the responsibility to do something...
7513    i was at home and i heard a loud sound of spit...
7514    i did not do the homework that the teacher had...
7515    i had shouted at my younger brother and he was...
Name: dokumen, Length: 7516, dtype: object

In [7]:
korpus = Corpus()
korpus.fit(sentences, window=10, ignore_missing=False)
# korpus.save('glove.model')

In [8]:
korpus.dictionary

{'on': 0,
 'days': 1,
 'when': 2,
 'i': 3,
 'feel': 4,
 'close': 5,
 'to': 6,
 'my': 7,
 'partner': 8,
 'and': 9,
 'other': 10,
 'friends': 11,
 'at': 12,
 'peace': 13,
 'with': 14,
 'myself': 15,
 'also': 16,
 'experience': 17,
 'a': 18,
 'contact': 19,
 'people': 20,
 'whom': 21,
 'regard': 22,
 'greatly': 23,
 'every': 24,
 'time': 25,
 'imagine': 26,
 'that': 27,
 'someone': 28,
 'love': 29,
 'or': 30,
 'could': 31,
 'serious': 32,
 'illness': 33,
 'even': 34,
 'death': 35,
 'had': 36,
 'been': 37,
 'obviously': 38,
 'unjustly': 39,
 'treated': 40,
 'no': 41,
 'possibility': 42,
 'of': 43,
 'elucidating': 44,
 'this': 45,
 'think': 46,
 'about': 47,
 'the': 48,
 'short': 49,
 'we': 50,
 'live': 51,
 'relate': 52,
 'it': 53,
 'periods': 54,
 'life': 55,
 'did': 56,
 'not': 57,
 'use': 58,
 'gathering': 59,
 'found': 60,
 'involuntarily': 61,
 'sitting': 62,
 'next': 63,
 'two': 64,
 'who': 65,
 'expressed': 66,
 'opinions': 67,
 'considered': 68,
 'very': 69,
 'low': 70,
 'discrimin

In [ ]:
# corpus_model = Corpus.load('glove.model')

In [9]:
korpus
# corpus_model

In [10]:
len(korpus.dictionary)

9352

In [11]:
korpus.matrix

<9352x9352 sparse matrix of type '<class 'numpy.float64'>'
	with 400898 stored elements in COOrdinate format>

In [12]:
glove = Glove(no_components=100, learning_rate=0.05, alpha=0.75, max_count=100, max_loss=10.0, random_state=None)
glove.fit(korpus.matrix)
glove.add_dictionary(korpus.dictionary)
glove.save('glove.model')


In [13]:
glove

In [14]:
glove.most_similar('i', number=10)

[('am', 0.9978951258932937),
 ('knew', 0.9975246572658713),
 ('couldnt', 0.9973085964050031),
 ('felt', 0.9967032203597578),
 ('whom', 0.9961916175461469),
 ('once', 0.9961453821121397),
 ('guilty', 0.9961383203447636),
 ('failed', 0.9960309686700327),
 ('found', 0.995962949342289)]

In [15]:
glove.word_vectors[glove.dictionary['me']]

array([-0.2634262 , -0.23958119, -0.08990405, -0.25639378,  0.24299291,
        0.24715168,  0.18415587, -0.15029599,  0.23541811,  0.27221706,
       -0.26665286,  0.20850714, -0.19432634, -0.09326368,  0.11387769,
       -0.23964981, -0.18578008, -0.15421777, -0.25829848, -0.28922803,
       -0.11436411, -0.20145626, -0.09945749, -0.29870199, -0.1670376 ,
       -0.10439499,  0.12769376, -0.10034001, -0.35504285,  0.14369338,
       -0.01895844, -0.17345976,  0.11717973,  0.15210385,  0.21278497,
        0.17528355,  0.18800252, -0.21110281, -0.14529023,  0.19352875,
       -0.06340648, -0.15493803, -0.02781375, -0.00088039, -0.3084181 ,
       -0.14862958, -0.03522046,  0.01569948, -0.23668028, -0.17026066,
        0.07567862,  0.09538676,  0.12730438,  0.26356423,  0.31847713,
        0.33986287, -0.13167366, -0.03821139, -0.12040468, -0.2341396 ,
       -0.34039929,  0.01023273,  0.26165291,  0.10863511, -0.22988536,
        0.0423545 ,  0.11985482, -0.25835153, -0.12755092, -0.09

In [16]:
glove.word_vectors

array([[-0.2056121 , -0.17679225, -0.0621422 , ...,  0.16801706,
         0.06737465,  0.13283869],
       [-0.0768231 , -0.06906408, -0.02099216, ...,  0.06204265,
         0.01033204,  0.04787559],
       [-0.28985902, -0.25889192, -0.03729695, ...,  0.22860317,
         0.0689619 ,  0.1879484 ],
       ...,
       [ 0.00774853,  0.00668689,  0.0038018 , ..., -0.01151478,
        -0.00275344, -0.00810476],
       [ 0.01103666,  0.01021814,  0.00598209, ..., -0.01277559,
        -0.00300024, -0.00288968],
       [ 0.00657692,  0.00273574,  0.00572482, ..., -0.00148784,
         0.0020353 , -0.00644256]])

In [17]:
glove.word_vectors.shape

(9352, 100)

In [18]:
glove.word_biases.shape

(9352,)

In [ ]:
# tes1='friends'
# tes2=['my', ' friend']
# tes3='my friend'

# glove.transform_paragraph(tes1)

In [19]:
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.scripts.glove2word2vec import get_glove_info
from gensim.models import Word2Vec
import gensim

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [21]:
get_glove_info('/content/glove.model')

(57834, 5)

In [27]:
glove_file = '/content/drive/MyDrive/glove.6B.100d.txt'
tmp_file = '/content/tes'

glove2word2vec(glove_file, tmp_file)

# KeyedVectors.load_word2vec_format dipakai jika c
model = KeyedVectors.load_word2vec_format(tmp_file)
# model = gensim.models.word2vec.Word2Vec.load(tmp_file)

In [29]:
model.wv.vectors

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


array([[-0.038194, -0.24487 ,  0.72812 , ..., -0.1459  ,  0.8278  ,
         0.27062 ],
       [-0.10767 ,  0.11053 ,  0.59812 , ..., -0.83155 ,  0.45293 ,
         0.082577],
       [-0.33979 ,  0.20941 ,  0.46348 , ..., -0.23394 ,  0.47298 ,
        -0.028803],
       ...,
       [ 0.36088 , -0.16919 , -0.32704 , ...,  0.27139 , -0.29188 ,
         0.16109 ],
       [-0.10461 , -0.5047  , -0.49331 , ...,  0.42527 , -0.5125  ,
        -0.17054 ],
       [ 0.28365 , -0.6263  , -0.44351 , ...,  0.43678 , -0.82607 ,
        -0.15701 ]], dtype=float32)

In [30]:
model.wv.vectors.shape

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  """Entry point for launching an IPython kernel.


(400000, 100)